config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end

  resources :direct_messages

  root to: "chatrooms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
    has_many :chatroom_users
    has_many :users, through: :chatroom_users
    has_many :messages
end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :chatroom_users
         has_many :chatrooms, through: :chatroom_users
         has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    end
  end

app/controllers/chatroom_users_controller.rb
class ChatroomUsersController < ApplicationController
    before_action :set_chatroom

    def create
        @chatroom_user = @chatroom.chatroom_users.where(user_id: current_user.id).first_or_create
        redirect_to @chatroom
    end

    def destroy
        @chatroom_user = @chatroom.chatroom_users.where(user_id: current_user.id).destroy_all
        redirect_to chatrooms_path
    end

    private

    def set_chatroom
        @chatroom = Chatroom.find(params[:chatroom_id])
        
    end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :set_chatroom, only: %i[ show edit update destroy ]

  # GET /chatrooms or /chatrooms.json
  def index
    @chatrooms = Chatroom.all
  end

  # GET /chatrooms/1 or /chatrooms/1.json
  def show
    @messages = @chatroom.messages.order(created_at: :desc).limit(100).reverse
  end

  # GET /chatrooms/new
  def new
    @chatroom = Chatroom.new
  end

  # GET /chatrooms/1/edit
  def edit
  end

  # POST /chatrooms or /chatrooms.json
  def create
    @chatroom = Chatroom.new(chatroom_params)

    respond_to do |format|
      if @chatroom.save
        format.html { redirect_to @chatroom, notice: "Chatroom was successfully created." }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chatrooms/1 or /chatrooms/1.json
  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to @chatroom, notice: "Chatroom was successfully updated." }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1 or /chatrooms/1.json
  def destroy
    @chatroom.destroy
    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: "Chatroom was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatroom
      @chatroom = Chatroom.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chatroom_params
      params.require(:chatroom).permit(:name)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_chatroom

    def create
        message = @chatroom.messages.new(message_params)
        message.user = current_user
        message.save
        redirect_to @chatroom
    end

    private 
    def set_chatroom
        @chatroom = Chatroom.find(params[:chatroom_id])
    end

    def message_params
        params.require(:message).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/views/chatrooms/_form.html.erb
<%= form_with(model: chatroom) do |form| %>
  <% if chatroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chatroom.errors.count, "error") %> prohibited this chatroom from being saved:</h2>

      <ul>
        <% chatroom.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chatrooms/edit.html.erb
<h1>Editing Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Show', @chatroom %> |
<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chatrooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chatrooms.each do |chatroom| %>
      <tr>
        <td><%= chatroom.name %></td>
        <td><%= link_to 'Show', chatroom %></td>
        <td><%= link_to 'Edit', edit_chatroom_path(chatroom) %></td>
        <td><%= link_to 'Destroy', chatroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= button_to 'Join', chatroom_chatroom_users_path(chatroom), method: :post %></td>
        <td><%= button_to 'Leave', chatroom_chatroom_users_path(chatroom), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chatroom', new_chatroom_path %>

app/views/chatrooms/new.html.erb
<h1>New Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @chatroom.name %>
</p>

<div data-behavior='messages'>
  <% @messages.each do |messages|%>
  <div><strong><%=messages.user.username%>: </strong> <%= messages.body %>
    <% end %>
</div>

<%= form_for [@chatroom, Message.new], remote: true do |f| %>
  <%= f.text_field :body, rows: 1, class: "form-control", autofocus: true %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            Chat
          <% end %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <%= yield :right_nav %>

              <li >
                <ul >
                <li><%= current_user.username %>
                  <li><%= link_to "Settings", edit_user_registration_path %></li>
                  <li><%= button_to "Sign out", destroy_user_session_path, method: :delete%></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path, method: :delete %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
     <div class="fluid-container" style="margin-top: 70px">
      <div class="row">
        <div class="col-sm-2" style="position: fixed; top: 70px; left: 0;">
          <% if user_signed_in? %>
            <h5>Chatrooms</h5>
            <ul>
            <% current_user.chatrooms.each do |chatroom| %>
                <li><%= link_to chatroom.name, chatroom %></li>
              <% end %>
            </ul>

            <h5>Users</h5>
            <ul>
            </ul>
          <% end %>
        </div>

        <div class="col-sm-10 col-sm-offset-2">
          <%= yield %>
        </div>
      </div>
    </div>

  </body>
</html>